dist: Xenial
language: node_js
node_js:
- lts/*
cache: npm
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: mohammedessehemy@gmail.com
  api_key:
    secure: ze3RMhjpwD4EPbkCURFTMgAEtnxLGDbYZzd7wI8GTa9yVphWGZTAJ8nakzfWA3O3nalLuWTmYCEag4aFhFFQ7hiHKs405nX//rx9tVRdhD71p/44tnVSAWfczymT9ZajsC3GkKxMaOd433CWV+wbt0zuvpCGn5yxn8vD9/LZV0wPOw4qb+fIfa6sOzYUKxQbavd+ltbjA4/QBTGU6rs40x69uO1z3bGDy7B7bfxBe3HhDboAjnJLk6mgn7BtXEFY4ScvAf2EVYvAmJV/aUp/tbw/jUqumkbWzpzUPJm1jV7uEwPwLXU45Xn6GOnm2V7ayJgFbFLPmrEHxZimL2oX5eJDKU0TDFkSqFPMd99L5nyxLSaIppYOn16OT5hYW4VbCzKG1arx6A3+UB+uF53gwvLjTv/TvvposF3OMrBOG3fpxM6qIlFeKPuVT72RpDNd/BJJSHREcwQKVBZjmb9EVy4+zjxwpwZcElWqWaoN1MCjqiNdk/kjF8P8n8RM73yLDtMKgahaOBShW4jA/xcwiWL7UwYz28XhomSMNu5wRGdz3huZoYG4Kmc4HZ9XS1O5yQrTJa9C4NuMyjOeGhSgURA9Dhg/AXPHsZyuKSwGg8VBamA+J/DicG6amfPK5JP/PjiDe0tZPgSbAJd3XE1qHkqyaZiVLUcOsoacl4PYCW4=
  on:
    branch: master
