dist: Xenial
language: node_js
node_js:
- lts/*
cache: npm
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: mohammedessehemy@gmail.com
  api_key:
    secure: bZ6Iu6LSj48VUjZRKQ7L3S9fpek4Bg5s8wh9lJr+tUW1h4UDYXa3AmQAaQFcg0nSGQupcx3lG5SRo1lRJMknVT0vAGAXc/gMJXvHTsnK0auUbiNfKKzdtlL0k3zvJpIkS5AmbhaQGpkgmurULpKweE//N3e+KFoRhso15M19dl/13CJFX+m8QIDpe1aHnBvM404vjgdlFUIJGH/Bv8bnuIk5upTZnwvXo/Vr8EiaqianDsx8h3x1Ub5kquE7GPlNCpx/dPzbf+V2tYieE+TNBBs0DYPJkCvMcEUIHkyj85L3D+Hz5xuoJA9OotzM9c9EAsaDWC0nPgA2gyJJmFJbaTyySmffE8XxUbj30GoTsHkEvenBdPJl4skcTfS+9R1DOKe8TtvFwWHPeXcW/v7C6ixuFsqZ9CR0qPkosa76JNS3wdRnLK/DjIaQb1u+BEZ2TM90goalk4uW54I+g5V2ccpDg2/7VeA56OuQDjR+VZwYGfciFeh/kHNkIfqEMSIZMlucfd3c5iB/Zeu0g7aTduTLfA3gdmGfKKuUXAweQRn+lR5Cjawjzz6GmkDq/sYgM/mYpe8FAxKgGmIkNXHVXZf0BRFeuwqD/W8Sz+BMnkfE5EJfldexkI8Dt59rUNCGAyv7pdm7HRB0iwsNZOrg6YvjeKIjc5GRDRwE+l3jxJg=
  on:
    branch: master
